# Generated by Django 3.2.5 on 2023-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
